name: CI
on:
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        name: Use Node.js 13.x
        with:
          node-version: '13.x'
          registry-url: 'https://npm.pkg.github.com'
      - uses: actions/cache@v1
        name: Restore node_modules cache
        id: node_modules
        with:
          path: node_modules
          key: ${{runner.os}}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{runner.os}}-node_modules
      - run: yarn install --frozen-lockfile
        if: steps.node_modules.outputs.cache-hit != 'true'
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - run: npm publish
        if: success() && startsWith(github.ref, 'refs/tags/')
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  build-examples:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        name: Use Node.js 13.x
        with:
          node-version: '13.x'
          registry-url: 'https://npm.pkg.github.com'
      - uses: actions/cache@v1
        name: Restore node_modules cache
        id: node_modules
        with:
          path: node_modules
          key: ${{runner.os}}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{runner.os}}-node_modules
      - run: yarn install --frozen-lockfile
        if: steps.node_modules.outputs.cache-hit != 'true'
      - run: yarn build-example
      - name: Deploy examples
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BASE_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: example # The folder the action should deploy.
